const fs = require('fs');

// Map of corrupted UTF-8 (double-encoded as latin1) to correct characters
// Generated by taking each common emoji/special char and computing how it appears when
// UTF-8 bytes are misread as latin-1 (windows-1252) and then re-saved as UTF-8
const fixes = [
  // Emojis (4-byte UTF-8, badly decoded twice)
  ['Ã°Å¸â€˜Â¨Ã¢â‚¬ÂÃ¢Å¡â€¢Ã¯Â¸Â', '👨‍⚕️'],  // 👨‍⚕️ doctor
  ['Ã°Å¸Âªâ€˜', '🪒'],   // 🪒 queue / clipboard emoji
  ['Ã°Å¸â€˜Â¨â€ÂÃ¢Å¡â€¢Ã¯Â¸Â', '👨‍⚕️'],
  ['Ã°Å¸â€Â¢', '🏢'],   // 🏢
  ['Ã°Å¸Â©Âº', '🩺'],   // 🩺 stethoscope
  ['Ã°Å¸â€œÂ·', '📷'],   // 📷 camera/QR
  ['Ã°Å¸â€"Â¨Ã¯Â¸Â', '🖨️'],  // 🖨️ printer
  ['Ã°Å¸â€Â', '🔍'],   // 🔍 magnify
  ['Ã°Å¸â€â€ž', '🔄'],   // 🔄 refresh
  ['Ã°Å¸ÂÂ¢', '🏢'],   // 🏢 building
  ['Ã°Å¸Å¡Âª', '🚪'],   // 🚪 door
  ['Ã°Å¸â€"â€˜', '📘'],   // 📘 book/trash
  ['Ã°Å¸â€˜Â©', '👩'],   // 👩
  ['Ã°Å¸â€˜Â¨', '👨'],   // 👨
  ['Ã°Å¸Â', '🏥'],
  ['Ã°Å¸', '🏥'],
  // Special symbols
  ['Ã¢â€ â€™', '→'],    // →
  ['Ã¢â€â‚¬', '--'],   // — em dash separator in comments
  ['Ã¢â€¢Â', '═'],    // ═ box drawing
  ['Ã¢Å"â€¦', '✅'],   // ✅ checkmark
  ['Ã¢Å"Â', '✏️'],    // ✏️ pencil
  ['Ã¢Å"â€¢', '✖'],   // ✖ cross/close
  ['Ã¢Å¾â€¢', '✾'],   // ✾ flourish / add
  ['Ã¢Å¡â„¢', '⚙'],   // ⚙ gear
  ['Ã¢Å¡â€¢', '⚕'],   // ⚕ medical
  ['Ã¯Â¸Â', '️'],     // variation selector
  ['Ã‚Â·', '·'],      // middle dot
  ['Ã¢â‚¬â€', '—'],   // em dash
  ['Ã¢â‚¬â€œ', '"'],   // left quote
  ['Ã¢â‚¬Â', '"'],    // right quote
];

const files = [
  'c:/Users/ASUS/Projects/MediQueue/mediqueue-backend/public/hospital.html',
  'c:/Users/ASUS/Projects/MediQueue/mediqueue-backend/public/dashboard.html',
];

files.forEach(fpath => {
  let content = fs.readFileSync(fpath, 'utf8');
  
  // Apply all replacements
  fixes.forEach(([bad, good]) => {
    content = content.split(bad).join(good);
  });
  
  // Show remaining corruption
  const remaining = content.match(/Ã[^\s<>"']{1,10}/g);
  if (remaining) {
    const unique = [...new Set(remaining)];
    console.log(`${fpath.split('/').pop()} - remaining corrupted sequences:`);
    unique.slice(0, 20).forEach(s => console.log('  ', JSON.stringify(s)));
  } else {
    console.log(`${fpath.split('/').pop()} - clean!`);
  }
  
  fs.writeFileSync(fpath, content, 'utf8');
});
